### ISSUE TITLE
Erro de consumo de Memória

### ISSUE THREAD

**Issue by dudufantastico** [novosga/novosga#303]
| Q                | A
| ---------------- | -----
| Bug report?      |
| Feature request? | 
| MySQL version    | 5.7.20
| PHP version      | 7.1.12
| Platform/OS      | centOs 7.4
| Novo SGA version | 2.0 RC1

Boa tarde instalamos a 2.0 RC1, porem quando chama a tela de login da o erro abaixo:

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/novosga20RC1/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /var/www/novosga20RC1/vendor/symfony/debug/Exception/OutOfMemoryException.php on line 1

já alteramos o parâmetro limit_memory do php, porem o erro persiste só vai mudando a quantidade de bytes consumida. chegamos a colocar -1 e o sistema demora e não abre.

Alguém já teve este problema e consegue dar uma luz?

**Comment by rogeriolino** [comment]
@dudufantastico 

Faça um teste adicionando o parâmetro `buffer_size` abaixo dessa linha https://github.com/novosga/novosga/blob/master/config/packages/prod/monolog.yaml#L5

(O arquivo acima se refere ao ambiente de produção, diretório **prod**)

Ex:

```yaml
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            buffer_size: 200
            handler: nested
```

Limpe o cache da aplicação:

    bin/console cache:clear

Ou especificando o stage:

    bin/console cache:clear --env=prod

Documentação do monolog bundle:
http://symfony.com/doc/current/reference/configuration/monolog.html
